title: Adam Niedzielski
description: Happy teams create great products
baseurl: ""
url: "https://blog.sundaycoding.com"
mastodon:
- username: adam_von_sonntag
  instance: chaos.social
github_username:  adamniedzielski
permalink: /blog/:year/:month/:day/:title/

theme: minima
plugins:
  - jekyll-feed
show_excerpts: true
