title: Adam Niedzielski
description: Happy teams create great products
baseurl: ""
url: "https://blog.sundaycoding.com"
twitter_username: niedzielskiadam
github_username:  adamniedzielski
permalink: /blog/:year/:month/:day/:title/

theme: minima
plugins:
  - jekyll-feed
